---

- name: Assert configuration
  assert:
    that:
      - aws_vpc_additional_block_cidr is not none and aws_vpc_additional_block_cidr | length > 0
      - aws_vpc_additional_block_cidr_subnet_private_a and aws_vpc_additional_block_cidr_subnet_private_a | length > 0
      - aws_vpc_additional_block_region is not none and aws_vpc_additional_block_region | length > 0
      - aws_vpc_additional_block_stack_name is not none and aws_vpc_additional_block_stack_name | length > 0
      - aws_vpc_additional_block_tags is not none and aws_vpc_additional_block_tags | length > 0
      - aws_vpc_additional_block_tags.Name is not none
      - aws_vpc_additional_block_vpc_id is not none and aws_vpc_additional_block_vpc_id | length > 0

- name: Assert private subnet c configuration is in sequence
  assert:
    that:
      - aws_vpc_additional_block_cidr_subnet_private_b is not none
      - aws_vpc_additional_block_cidr_subnet_private_b | length > 0
  when:
    - aws_vpc_additional_block_cidr_subnet_private_c is not none
    - aws_vpc_additional_block_cidr_subnet_private_c | length > 0

- name: Assert public subnet b configuration is in sequence
  assert:
    that:
      - aws_vpc_additional_block_cidr_subnet_public_a is not none
      - aws_vpc_additional_block_cidr_subnet_public_a | length > 0
  when:
    - aws_vpc_additional_block_cidr_subnet_public_b is not none
    - aws_vpc_additional_block_cidr_subnet_public_b | length > 0

- name: Assert public subnet c configuration is in sequence
  assert:
    that:
      - aws_vpc_additional_block_cidr_subnet_public_b is not none
      - aws_vpc_additional_block_cidr_subnet_public_b | length > 0
  when:
    - aws_vpc_additional_block_cidr_subnet_public_c is not none
    - aws_vpc_additional_block_cidr_subnet_public_c | length > 0

- name: Assert that a public subnet is present if an IGW has been specified
  assert:
    that:
      - aws_vpc_additional_block_cidr_subnet_public_a is not none
      - aws_vpc_additional_block_cidr_subnet_public_a | length > 0
  when:
    - aws_vpc_additional_block_internet_gateway_id is not none
    - aws_vpc_additional_block_internet_gateway_id | length > 0

- name: Ensure VPC Additional Block Stack
  cloudformation:
    region: "{{ aws_vpc_additional_block_region }}"
    stack_name: "{{ aws_vpc_additional_block_stack_name }}"
    state: present
    tags: "{{ aws_vpc_additional_block_tags }}"
    template: "{{ role_path }}/files/vpc_additional_block.yml"
    template_parameters:
      Cidr: "{{ aws_vpc_additional_block_cidr }}"
      CidrPrivateSubnetA: "{{ aws_vpc_additional_block_cidr_subnet_private_a }}"
      CidrPrivateSubnetB: "{{ aws_vpc_additional_block_cidr_subnet_private_b if aws_vpc_additional_block_cidr_subnet_private_b else '' }}"
      CidrPrivateSubnetC: "{{ aws_vpc_additional_block_cidr_subnet_private_c if aws_vpc_additional_block_cidr_subnet_private_c else '' }}"
      CidrPublicSubnetA: "{{ aws_vpc_additional_block_cidr_subnet_public_a if aws_vpc_additional_block_cidr_subnet_public_a else '' }}"
      CidrPublicSubnetB: "{{ aws_vpc_additional_block_cidr_subnet_public_b if aws_vpc_additional_block_cidr_subnet_public_b else '' }}"
      CidrPublicSubnetC: "{{ aws_vpc_additional_block_cidr_subnet_public_c if aws_vpc_additional_block_cidr_subnet_public_c else '' }}"
      InternetGatewayID: "{{ aws_vpc_additional_block_internet_gateway_id if aws_vpc_additional_block_internet_gateway_id else '' }}"
      Name: "{{ aws_vpc_additional_block_tags.Name }}"
      Region: "{{ aws_vpc_additional_block_region }}"
      VpcID: "{{ aws_vpc_additional_block_vpc_id }}"
  register: aws_vpc_additional_block_cf_output

- name: Set output facts
  set_fact:
    aws_vpc_additional_block_output: "{{ aws_vpc_additional_block_output | combine({
      aws_vpc_additional_block_tags.Name: aws_vpc_additional_block_cf_output
    }) }}"
